language: node_js

node_js:
  - "11"
  - "10"
  - "8"

cache: npm

before_script:
  - if [ $TRAVIS_NODE_VERSION == "10" ] then;
      commitlint-travis;
      npm run lint;
    fi

script:
  - npm test
  - if [ $TRAVIS_NODE_VERSION == "10" ] then;
      npm run test:coverage:report;
      npm run build;
    fi

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+(-\d+)?$/ # e.g. `v3.2.1` | `v3.2.1-0`

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: "10"

notifications:
  email: false
