language: node_js

node_js:
  - "node"
  - "lts/*"

cache:
  directories:
    - "$HOME/.npm"

before_install:
  # `npm ci` is available since npm@5.7.0
  - if [[ $TRAVIS_NODE_VERSION == lts/* ]]; then npm i -g npm@latest; fi

before_script:
  - commitlint-travis
  - npm run lint

after_success:
  - npm run build

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+(-\d+)?$/ # e.g. `v3.2.1` | `v3.2.1-0`

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: "lts/*"

notifications:
  email: false
