name: npm diff

on:
  pull_request_target:
    types: [opened]

jobs:
  npm-diff:
    if: ${{ startsWith(github.head_ref, 'dependabot/npm_and_yarn/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: ybiquitous/npm-diff-action@60e7d34d17945170e7bce8d79dd58c28166caf8e # v1.7.1
